# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pr:
- master
- dev

jobs: 
  - job: default
    pool:
        name: Hosted
        demands: Cmd
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.1.300'
    - task: AzurePowerShell@4
      version: 1.0.1
      displayName: 'Build and test'
      inputs:
        filename: scripts/build.ps1
        arguments: '-configuration Debug -arch x86 -ci'